export default {
  casi_da_screening: 'casiDaScreening',
  casi_da_sospetto_diagnostico: 'casiDaSospettoDiagnostico',
  casi_testati: 'casiTestati',
  data: 'giorno',
  deceduti: 'deceduti',
  dimessi_guariti: 'dimessiGuariti',
  isolamento_domiciliare: 'isolamentoDomiciliare',
  note: 'note',
  nuovi_positivi: 'nuoviPositivi',
  ricoverati_con_sintomi: 'ricoveratiConSintomi',
  stato: 'stato',
  tamponi_giornalieri: 'tamponiGiornalieri',
  tamponi: 'tamponi',
  terapia_intensiva: 'terapiaIntensiva',
  totale_casi: 'totaleCasi',
  totale_ospedalizzati: 'totaleOspedalizzati',
  totale_positivi: 'totalePositivi',
  variazione_totale_positivi: 'variazioneTotalePositivi',
};
